Repository fluencelabs/aquavm, pull requests merged in 2022-05, with the labels that each got.

#260 Update readme
  README.md
  images/aquamarine.png
  images/aquavm_air_model.png
  images/call.png
  images/call_data.png
  images/fold.png
  images/fold_example.png
  images/interpreter.png
  images/interpreter_execution_model.png
  images/null.png
  images/par.png
  images/seq.png
  images/stack.png
  images/xor.png
Labels: C-docs

#262 Use pooled AVMRunner for tests
  Cargo.lock
  air/tests/test_module/features/tetraplets/security_tetraplets/auth_module/Cargo.lock
  air/tests/test_module/features/tetraplets/security_tetraplets/log_storage/Cargo.lock
  avm/server/src/runner.rs
  crates/air-lib/test-utils/Cargo.toml
  crates/air-lib/test-utils/src/test_runner.rs
Labels: A-tests, C-dx

#265 Rename subtree to subgraph
  CHANGELOG.md
  air/src/execution_step/air/call/call_result_setter.rs
  air/src/execution_step/air/call/prev_result_handler.rs
  air/src/execution_step/air/call/resolved_call.rs
  air/src/execution_step/air/fail.rs
  air/src/execution_step/air/fold_stream.rs
  air/src/execution_step/air/mod.rs
  air/src/execution_step/air/par.rs
  air/src/execution_step/air/par/completeness_updater.rs
  air/src/execution_step/air/seq.rs
  air/src/execution_step/air/xor.rs
  air/src/execution_step/execution_context/context.rs
  air/src/execution_step/execution_context/scalar_variables.rs
  air/tests/test_module/features/errors/last_error.rs
  air/tests/test_module/issues/issue_178.rs
  air/tests/test_module/issues/issue_180.rs
  crates/air-lib/interpreter-data/src/executed_state/impls.rs
  crates/air-lib/log-targets/src/lib.rs
  crates/air-lib/trace-handler/README.md
  crates/air-lib/trace-handler/src/handler.rs
  crates/air-lib/trace-handler/src/lib.rs
  crates/air-lib/trace-handler/src/merger/fold_merger/fold_lore_resolver.rs
  crates/air-lib/trace-handler/src/state_automata/errors.rs
  crates/air-lib/trace-handler/src/state_automata/fold_fsm/state_handler.rs
  crates/air-lib/trace-handler/src/state_automata/mod.rs
  crates/air-lib/trace-handler/src/state_automata/par_fsm.rs
  crates/air-lib/trace-handler/src/state_automata/par_fsm/par_builder.rs
  crates/air-lib/trace-handler/src/state_automata/par_fsm/state_handler.rs
  crates/air-lib/trace-handler/src/state_automata/par_fsm/state_handler/new_states_calculation.rs
Labels: С-naming

#266 `beautifier` and `air-beautify` crates
  Cargo.lock
  Cargo.toml
  crates/beautifier/Cargo.toml
  crates/beautifier/src/beautifier.rs
  crates/beautifier/src/lib.rs
  crates/beautifier/src/tests/beautifier.rs
  crates/beautifier/src/tests/deeply_nested.air
  crates/beautifier/src/tests/deeply_nested_expected.txt
  crates/beautifier/src/tests/mod.rs
  tools/cli/air-beautify/Cargo.toml
  tools/cli/air-beautify/src/main.rs
Labels: C-feature
