Repository fluencelabs/aquavm, pull requests merged in 2023-08, with the labels that each got.

#643 chore(tests): test case for #642
  air/tests/test_module/issues/issue_642.rs
  air/tests/test_module/issues/mod.rs
Labels: A-trace-handler, A-execution-engine, e2e

#649 feat(execution-engine)!: update minimal interpreter version
  air/src/preparation_step/interpreter_versions.rs
Labels: A-execution-engine, e2e

#650 chore(tests): fix version checking tests
  air/src/lib.rs
  air/src/preparation_step/mod.rs
  air/tests/test_module/features/misc/version_check.rs
Labels: e2e

#651 chore(tests): fix publish_version_check test
  air/tests/test_module/features/misc/version_check.rs
Labels: e2e

#653 chore: fix code formatting
  air/src/lib.rs
  air/tests/test_module/features/misc/version_check.rs
Labels: e2e

#654 chore: Speedup CI
  .github/workflows/lint-pr.yml
  .github/workflows/lint.yml
  .github/workflows/run-tests.yml
  .github/workflows/snapshot-air-beautify-wasm.yml
  .github/workflows/snapshot-air-interpreter-wasm.yml
  .github/workflows/snapshot-cargo.yml
  .github/workflows/snapshot.yml
  .github/workflows/tests.yml
Labels: e2e

#655 chore: Run e2e on merge to master
  .github/workflows/e2e.yml
Labels: e2e

#658 chore: Save cache in cargo snapshot workflow
  .github/workflows/snapshot-air-interpreter-wasm.yml
  .github/workflows/snapshot-cargo.yml
Labels: e2e

#663 chore: Bump fluence-app-service to 0.27.0
  Cargo.lock
  air/Cargo.toml
Labels: e2e

#664 feat(execution-engine): rename boxed_values into value_types
  air/src/execution_step/execution_context/scalar_variables.rs
  air/src/execution_step/execution_context/stream_maps_variables.rs
  air/src/execution_step/instructions/ap/apply_to_arguments.rs
  air/src/execution_step/instructions/call/resolved_call.rs
  air/src/execution_step/instructions/canon.rs
  air/src/execution_step/instructions/canon_stream_map_scalar.rs
  air/src/execution_step/instructions/canon_utils/mod.rs
  air/src/execution_step/instructions/fold/mod.rs
  air/src/execution_step/instructions/fold/utils.rs
  air/src/execution_step/instructions/fold_scalar.rs
  air/src/execution_step/instructions/fold_stream.rs
  air/src/execution_step/instructions/fold_stream/stream_execute_helpers.rs
  air/src/execution_step/instructions/mod.rs
  air/src/execution_step/mod.rs
  air/src/execution_step/resolver/resolvable_impl.rs
  air/src/execution_step/value_types/canon_stream.rs
  air/src/execution_step/value_types/iterable.rs
  air/src/execution_step/value_types/iterable/canon_stream.rs
  air/src/execution_step/value_types/iterable/lambda_result.rs
  air/src/execution_step/value_types/iterable/resolved_call.rs
  air/src/execution_step/value_types/iterable/vec_resolved_call.rs
  air/src/execution_step/value_types/jvaluable.rs
  air/src/execution_step/value_types/jvaluable/canon_stream.rs
  air/src/execution_step/value_types/jvaluable/cell_vec_resolved_call_result.rs
  air/src/execution_step/value_types/jvaluable/iterable_item.rs
  air/src/execution_step/value_types/jvaluable/resolved_call_result.rs
  air/src/execution_step/value_types/mod.rs
  air/src/execution_step/value_types/scalar.rs
  air/src/execution_step/value_types/scalar/values.rs
  air/src/execution_step/value_types/stream/mod.rs
  air/src/execution_step/value_types/stream/recursive_stream.rs
  air/src/execution_step/value_types/stream/stream_definition.rs
  air/src/execution_step/value_types/stream/values_matrix.rs
  air/src/execution_step/value_types/stream_map.rs
  air/src/execution_step/value_types/utils.rs
Labels: A-execution-engine, C-refactoring, e2e

#666 chore: Add e2e label as fluencebot to trigger e2e
  .github/workflows/e2e-label.yml
Labels: e2e

#671 chore(aquavm-air-cli): dedicated type for execution mode
  tools/cli/air/src/trace/run.rs
Labels: C-refactoring, e2e

#676 chore: `PartialOrd` uses `Ord`'s implementation
  crates/air-lib/air-parser/src/parser/span.rs
Labels: P-low, A-air-parser, C-refactoring, e2e

#674 feat(polyplets)!: move SecurityTetraplets to marine-rs-sdk
  Cargo.lock
  Cargo.toml
  air/src/execution_step/instructions/call/resolved_call.rs
  crates/air-lib/polyplets/Cargo.toml
  crates/air-lib/polyplets/src/lib.rs
  crates/air-lib/polyplets/src/tetraplet.rs
  crates/air-lib/polyplets/src/triplet.rs
Labels: e2e

#672 feat(aquavm-air-cli): `--near` execution mode [fixes VM-322]
  .github/release-please/config.json
  Cargo.lock
  air/Cargo.toml
  avm/server/Cargo.toml
  crates/air-lib/interpreter-signatures/Cargo.toml
  tools/cli/air/Cargo.toml
  tools/cli/air/README.md
  tools/cli/air/src/trace/run.rs
  tools/cli/air/src/trace/run/near.rs
  tools/wasm/air-near-contract/Cargo.lock
  tools/wasm/air-near-contract/Cargo.toml
  tools/wasm/air-near-contract/build.sh
  tools/wasm/air-near-contract/rust-toolchain.toml
  tools/wasm/air-near-contract/src/lib.rs
Labels: P-medium, C-feature, e2e

#678 chore(ci): fix release-please config
  .github/release-please/config.json
Labels: A-CI, e2e

#679 fix(aquavm-air-cli): NEAR mode fixes
  Cargo.lock
  tools/cli/air/src/trace/run.rs
  tools/cli/air/src/trace/run/near.rs
  tools/wasm/air-near-contract/Cargo.lock
Labels: C-bug, P-high, e2e

#677 feat(execution-engine)!: this introduces a hardcoded limit for a number of values in a stream [fixes VM-324]
  air/src/execution_step/errors/uncatchable_errors.rs
  air/src/execution_step/execution_context/stream_maps_variables.rs
  air/src/execution_step/execution_context/streams_variables.rs
  air/src/execution_step/instructions/ap.rs
  air/src/execution_step/instructions/ap_map.rs
  air/src/execution_step/instructions/call/call_result_setter.rs
  air/src/execution_step/mod.rs
  air/src/execution_step/value_types/mod.rs
  air/src/execution_step/value_types/stream/mod.rs
  air/src/execution_step/value_types/stream/recursive_stream.rs
  air/src/execution_step/value_types/stream/stream_definition.rs
  air/src/execution_step/value_types/stream/values_matrix.rs
  air/src/execution_step/value_types/stream_map.rs
  air/tests/test_module/features/streams/recursive_streams.rs
  air/tests/test_module/negative_tests/uncatchable_trace_unrelated.rs
Labels: C-enhancement, A-execution-engine, e2e

#682 feat(execution-engine,interpreter-data)!: insert state for canon join
  air/src/execution_step/instructions/canon.rs
  air/src/execution_step/instructions/canon_stream_map_scalar.rs
  air/src/execution_step/instructions/canon_utils/mod.rs
  air/src/execution_step/value_types/stream/stream_definition.rs
  air/src/execution_step/value_types/stream_map.rs
  air/tests/test_module/instructions/canon.rs
  air/tests/test_module/negative_tests/uncatchable_trace_related.rs
  crates/air-lib/interpreter-data/src/executed_state.rs
  crates/air-lib/interpreter-data/src/executed_state/impls.rs
  crates/air-lib/test-utils/src/executed_state.rs
  crates/air-lib/test-utils/src/lib.rs
  crates/air-lib/trace-handler/src/merger/canon_merger.rs
Labels: C-enhancement, P-high, A-execution-engine, e2e
