Repository fluencelabs/aquavm, pull requests merged in 2023-11, with the labels that each got.

#723 chore(testing-framework): a new behavior to print service call parameters/result out to console
  air/tests/test_module/features/errors/error.rs
  crates/testing-framework/src/asserts/behavior.rs
  crates/testing-framework/src/asserts/mod.rs
  crates/testing-framework/src/asserts/parser.rs
  crates/testing-framework/src/execution/mod.rs
Labels: P-low, C-feature, e2e

#753 fix(air-interpreter): enable multiple invoke_tracing calls for air-interpreter
  air-interpreter/src/logger.rs
  air-interpreter/src/marine.rs
Labels: P-high, e2e, A-air-interpreter

#754 chore(tests): etalon benchmarking test for network team convenience
  air/Cargo.toml
  air/benches/nox_tc2_benchmark.rs
Labels: P-medium, A-tests, e2e

#755 chore: Update e2e [fixes FLU-480]
  .github/workflows/e2e.yml
  .github/workflows/release.yml
  .github/workflows/rustdoc.yml
Labels: e2e

#722 feat(interpreter-cid,interpreter-data)!: Support for mulitple hash types in CID verification
  air/tests/test_module/features/signatures/corruption.rs
  crates/air-lib/interpreter-cid/Cargo.toml
  crates/air-lib/interpreter-cid/src/lib.rs
  crates/air-lib/interpreter-cid/src/verify.rs
  crates/air-lib/interpreter-data/src/cid_store.rs
Labels: C-enhancement, P-medium, e2e

#758 chore: Add benchmark workflow
  .github/workflows/benchmark.yml
  .github/workflows/release.yml
  .github/workflows/run-tests.yml
Labels: e2e

#759 chore(benchmarks): call-requests and call-results benchmarks
  Cargo.lock
  air/src/execution_step/instructions/call/resolved_call.rs
  benches/PERFORMANCE.json
  benches/PERFORMANCE.txt
  junk/gen-bench-data/Cargo.toml
  junk/gen-bench-data/gen_benchmark_data.sh
  junk/gen-bench-data/src/calls.rs
  junk/gen-bench-data/src/main.rs
  tools/cli/air/src/trace/run.rs
  tools/cli/performance_metering/performance_metering/bench.py
Labels: P-high, A-tests, C-performance, T-optimization, e2e

#762 chore(benchmark): restore parser-10000-100 bench
  benches/PERFORMANCE.json
  benches/PERFORMANCE.txt
  junk/gen-bench-data/gen_benchmark_data.sh
  junk/gen-bench-data/src/main.rs
  junk/gen-bench-data/src/parser_10000_100.air
Labels: C-enhancement, P-low, A-tests, T-optimization, e2e
