Repository fluencelabs/aquavm, pull requests merged in 2023-06, with the labels that each got.

#597 chore(ci): remove redundant build.profiler
  .cargo/config.toml
Labels: A-CI, e2e

#605 feat(air-interpreter-signatures): use (de)serialize_with
  crates/air-lib/interpreter-signatures/src/lib.rs
  crates/air-lib/interpreter-signatures/src/sede.rs
Labels: C-enhancement, A-execution-engine, C-performance, e2e

#609 chore(testing-framework)!: restore WASM test executor
  air/benches/call_benchmark.rs
  air/benches/chat_benchmark.rs
  air/benches/create_service_benchmark.rs
  air/benches/data_big_benchmark.rs
  air/benches/data_long_benchmark.rs
  air/tests/test_module/features/cid/canon.rs
  air/tests/test_module/features/cid/mod.rs
  air/tests/test_module/features/lambda/functors.rs
  air/tests/test_module/features/signatures.rs
  air/tests/test_module/features/streams/merging.rs
  air/tests/test_module/features/tetraplets/provenance.rs
  air/tests/test_module/features/tetraplets/security_tetraplets.rs
  air/tests/test_module/issues/issue_178.rs
  air/tests/test_module/issues/issue_211.rs
  air/tests/test_module/issues/issue_221.rs
  air/tests/test_module/issues/issue_304.rs
  air/tests/test_module/issues/issue_356.rs
  benches/performance_metering/big_values_data/prev_data.json
  benches/performance_metering/dashboard/cur_data.json
  benches/performance_metering/dashboard/prev_data.json
  benches/performance_metering/long_data/cur_data.json
  benches/performance_metering/multiple-cids10/cur_data.json
  benches/performance_metering/multiple-cids10/prev_data.json
  benches/performance_metering/multiple-cids50/cur_data.json
  benches/performance_metering/multiple-cids50/prev_data.json
  benches/performance_metering/multiple-peers14/cur_data.json
  benches/performance_metering/multiple-peers14/prev_data.json
  benches/performance_metering/multiple-peers5/cur_data.json
  benches/performance_metering/multiple-peers5/prev_data.json
  benches/performance_metering/network_explore/cur_data.json
  benches/performance_metering/network_explore/prev_data.json
  crates/air-lib/test-utils/src/lib.rs
  crates/air-lib/test-utils/src/test_runner.rs
  crates/air-lib/test-utils/src/wasm_test_runner.rs
  crates/testing-framework/Cargo.toml
  crates/testing-framework/src/ephemeral/mod.rs
  crates/testing-framework/src/ephemeral/neighborhood.rs
  crates/testing-framework/src/execution/mod.rs
  crates/testing-framework/src/queue.rs
  crates/testing-framework/src/transform/walker.rs
Labels: A-tests, T-testing, e2e

#613 feat!: set nodejs target for air-beautify
  .github/workflows/release.yml
  tools/wasm/air-beautify-wasm/src/lib.rs
Labels: e2e

#617 chore(core): fix variable checking
  air/src/preparation_step/interpreter_versions.rs
Labels: e2e

#608 chore(execution-engine): additional StreamMap positive tests [fixes VM-295]
  air/tests/test_module/features/lambda/functors.rs
  air/tests/test_module/instructions/ap.rs
  air/tests/test_module/instructions/fold.rs
Labels: A-tests, A-execution-engine, e2e

#610 feat(execution-engine)!: stream map to scalar conversion using canon instruction [fixes VM-294]
  air/src/execution_step/boxed_value/stream.rs
  air/src/execution_step/boxed_value/stream_map.rs
  air/src/execution_step/execution_context/stream_maps_variables/stream_map_key.rs
  air/src/execution_step/instructions/canon.rs
  air/src/execution_step/instructions/canon_stream_map_scalar.rs
  air/src/execution_step/instructions/mod.rs
  air/tests/test_module/instructions/canon.rs
  crates/air-lib/air-parser/src/ast/instructions.rs
  crates/air-lib/air-parser/src/ast/instructions/impls.rs
  crates/air-lib/air-parser/src/ast/instructions/traits.rs
  crates/air-lib/air-parser/src/parser/air.lalrpop
  crates/air-lib/air-parser/src/parser/air.rs
  crates/air-lib/air-parser/src/parser/tests/canon.rs
  crates/air-lib/air-parser/src/parser/tests/dsl.rs
  crates/air-lib/air-parser/src/parser/validator.rs
  crates/beautifier/src/beautifier.rs
Labels: P-high, A-new-instruction, C-feature, A-execution-engine, e2e
